--- 
blank_issues_enabled: false
contact_links: 
  - 
    about: "To get support write a E-Mail to the linked support E-Mail on our website"
    name: "Support channel"
    url: "https://betterautostart.com"
